<x-admin-layout>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero et aperiam quo temporibus voluptatum! Dolorum voluptas dolor voluptatem nemo iusto molestias ipsum tempore magni beatae modi! Quo laboriosam quidem perferendis.</p>
    <p>Nobis ducimus saepe nemo. Voluptate tempore, optio delectus omnis fuga tenetur quis natus provident quas voluptatibus neque explicabo rerum atque illum, debitis voluptates molestiae doloribus itaque sunt. Repellendus, ab amet.</p>
    <p>Molestiae officiis hic aut alias, repudiandae nihil minima exercitationem tenetur, sed perspiciatis voluptas est animi autem laudantium amet earum! Quis deserunt, natus nisi suscipit earum quia dolorem tenetur impedit voluptatum?</p>
    <p>Obcaecati expedita illo sint aut ad ab provident molestiae aliquam debitis magnam culpa odit est facere perspiciatis dolorem perferendis architecto nam veritatis, hic porro quas deserunt quae neque. Delectus, aut.</p>
    <p>Nostrum, cum id? Quis facilis vero, sapiente eveniet nulla quas eum praesentium fuga amet mollitia animi dolorem sed reiciendis laborum est. Repellendus quidem delectus molestiae error eum deserunt? Vero, ratione?</p>
    <p>Doloribus veritatis nulla natus praesentium totam adipisci molestias eveniet nesciunt velit, minima commodi consequuntur, ullam similique at est eius modi. Vitae minus suscipit, accusamus illum deleniti dolor facere totam laborum.</p>
    <p>Asperiores, suscipit sint consequatur eius quasi dicta eveniet assumenda minus ipsa necessitatibus deserunt, modi eligendi iste laborum explicabo numquam cum, alias aut veniam quo consectetur. Velit officiis fuga provident totam.</p>
    <p>Qui odio enim eos, quasi natus accusantium dolor, doloribus quis illo harum deleniti expedita ipsam inventore placeat rem maxime quas amet sapiente voluptatibus. Quos, maxime illo! Beatae, velit officiis. Est!</p>
    <p>Ad, nemo dolores. Aut nobis doloremque alias! Nesciunt quae, error aut alias ullam perspiciatis, eaque dicta vel esse, voluptatibus similique modi ipsa? Quas, perferendis iure? Soluta quas tenetur quo labore!</p>
    <p>Voluptatem, eius! Vel quaerat aliquam quia qui labore non nam illo necessitatibus eligendi doloribus a laboriosam consectetur ratione, quis fugit tenetur pariatur corrupti harum porro deleniti nemo incidunt. Temporibus, cumque.</p>
    <p>Recusandae non, voluptas error iusto, odit earum doloremque blanditiis temporibus nostrum aliquid debitis corporis quibusdam, laboriosam in animi consequatur voluptatem necessitatibus voluptate cum aspernatur consequuntur repellendus maiores vero. Reprehenderit, cum.</p>
    <p>Quaerat velit doloremque fugiat veritatis, placeat dignissimos laborum nam distinctio facilis explicabo neque! Libero ut sunt repellat optio porro dolores. Quidem corporis suscipit impedit aut fugit ducimus dicta, natus ratione?</p>
    <p>Inventore sequi tempora illum reprehenderit nisi sed veritatis blanditiis dicta iure, nulla maxime commodi natus! Blanditiis, eum doloribus. Odio aut reprehenderit enim perferendis debitis unde alias nostrum nam consectetur omnis.</p>
    <p>Magni eos aliquid reiciendis totam, molestias quam adipisci expedita aliquam quis ut. Quos quibusdam quam facilis quo? Architecto dolores libero earum quisquam aspernatur saepe beatae doloremque, blanditiis placeat, doloribus laudantium.</p>
    <p>Itaque adipisci modi aut tenetur quis eaque animi sit dolorem repellat eos, corrupti magni iusto quam cumque exercitationem vero est. Sit reiciendis eius esse hic quia rem modi magnam saepe.</p>
    <p>Nulla soluta repudiandae totam quis facilis in fugit saepe distinctio tempore voluptatum sapiente, labore vitae dolor at autem mollitia natus eum, omnis nobis praesentium culpa optio cumque. Quam, officia aut.</p>
    <p>Eaque iusto minima odio quas assumenda nam quidem deserunt fugit corrupti, fugiat impedit quibusdam ipsum? Reprehenderit mollitia aut eos dicta eligendi sunt in maxime. Repudiandae rerum labore magni ratione maxime?</p>
    <p>Expedita architecto laborum provident dolores error porro aperiam nobis labore magni ullam fuga dolor, quas, corporis doloribus consectetur iste in, sit adipisci nam? Provident atque recusandae quae quaerat accusantium corrupti!</p>
    <p>Quia blanditiis architecto, corporis dicta quas tenetur numquam enim accusantium maxime magni excepturi et, debitis minus. Tempora nostrum similique, adipisci, reprehenderit fuga aliquid facilis sequi doloremque molestiae soluta odit? Consequatur!</p>
    <p>Velit sit temporibus eos esse tempora dolores praesentium, id ratione! Dolorum vero dolores sequi reiciendis illum labore consequuntur. Vero a laboriosam debitis officia nostrum quo laborum voluptas corporis eligendi aut?</p>
</x-admin-layout>